# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java-build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=shaazAhmed91_DevSecops_Pipeline -Dsonar.organization=shaazAhmed91 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a5801584d7990063dc61db9ad60f4b7f3f62925c
